apiVersion: v1
kind: Service
metadata:
  name: weaviate-pprof
  namespace: weaviate
spec:
  selector:
    app: weaviate
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060
  type: LoadBalancer
